### ISSUE TITLE
Directory structure review

### ISSUE THREAD

**Issue by Youngestdev** [simple-lang/rfcs#1]
So, the [simple-lang repo](https://github.com/simple-lang/simple), comprises of the environments and the modules needed for the installation of simple. But, the environment I believe should be on it's own. The main repo should only install the compiler and it's core modules leaving out the enviroment. This, enables developers work on each environment in its' repo instead of committing into the base branch, that can cause pollution. 

Therefore, I propose that the new directory structure for the main repository should be. 

+ .github
+  build
+ examples
+ modules
+ simple
+ ...

> Perhaps, In the future, the `examples` folder might be removed too, it really shouldn't be installed or be part of the main installation process.

**Comment by Youngestdev** [comment]
@Thecarisma, can you check this ?

**Comment by Thecarisma** [comment]
This has been implemented
