### ISSUE TITLE
[RFC] Overload Parameter Names as Argument Labels (for Controlling Optional Arguments)

### ISSUE THREAD

**Issue by synergixe** [simple-lang/rfcs#2]
The current standing of **simple lang** is that for function blocks (standalone or class), the parameter names are delineated in a sequence and have to be passed in such sequence as arguments during a call to such a function.

_Synergixe_ hopes to sponsor an RFC that changes this slightly and adds the concept of `Argument Labels` (derived from Swift programming language) into the simple language.

>Code Examples

```simple

#basic way to define a function (with default argument value - primitive data types ONLY)

block printStr(text, suffix = "", pos = 0)
	if lengthOf(suffix) > 0 {
		text = text + suffix
        }

	stdout.println(text)

#proposed way via overloading parameter names as argument labels

block printStr(:text, :suffix, :pos)
	if lengthOf(suffix) > 0 {
		text = text + suffix
        }

	stdout.println(text)


# calling without argument labels (you see we had to setup an argument value for the parameter - suffix)
printStr("Helloworld", " ?", 5)


# calling with argument labels (no need to setup an argument value for the parameter - suffix)
printStr(text; "Helloworld", pos; 5)

```

This is proposed as a better way to deal with optional parameters (argument values) that are not at either end of the argument list. This is better other alternatives proposed in languages like _JavaScript_

The argument labels also helps increase readability

What do you think ?

**Comment by Thecarisma** [comment]
### basic way to define a function (with default argument value - primitive data types ONLY)

Optional parameter is a load on the Virtual Machine and can affect speed and efficiency, the VM will have to call the functions with the optional parameter value if it not provide e.g 

```simple
block printStr(text, suffix = "", pos = 0)
	if lengthOf(suffix) > 0 {
		text = text + suffix
        }

	stdout.println(text)
``` 

If the function above **printStr** is invoked with only the text argument the VM will have to automatically call the function on behave on the developer with the the optional parameters in place 

**in the source code**
```simple
printStr("Hello World")
```

**translates to**
```simple
printStr("Hello World", "", 0)
```

This implies the VM has to keep record of the optional parameters which will cost more resources as the optional parameter will remain in memory until the function is garbage collected (when there exist no reference to the function therein).

### proposed way via overloading parameter names as argument labels

This is just another layer of complexity to the language, using a label in the parameter will make the function less readable as function call itself will appear as if it the declaration.

## Solution to the above 

The intents above can be achieved by using the list and variadic parameter. List is simple-lang is pure and can hold any other data types. List can also act as dictionary which make a lot of sense in this case.

The function can be declared with just one parameter which is list and the optional parameter can be 
sent as a list item or just ignored e.g 

```
block printStr(params)
        text = params["text"]
        suffix = params["suffix"]
        pos = params["pos"]

	if lengthOf(suffix) > 0 {
		text = text + suffix
        }

	stdout.println(text)
```

The above can be invoke with all the optional parameters (text, suffix, pos) intact or ignored. The following function call below is valid

```
printStr([ :text = "Hello World", :suffix = ".txt", :pos = 20 ])
printStr([ :text = "Hello World", :suffix = ".txt" ])
printStr([ :text = "Hello World" ])
printStr([])
```

The default value for no existing key index is null e.g. params["alien"] == null. 
Everything comes with a draw back, the drawback of using list is that the non existing key will be created which might cost some memory allocation but it is garbage collected at the end of execution of the function in contrast to the optional parameter which will have to exist even after the function has complete or even through out runtime.

**Comment by Thecarisma** [comment]
Next time make the rfc into PR using the [template](https://github.com/simple-lang/rfcs/blob/master/0000-template.md). Follow the instruction on the readme [here](https://github.com/simple-lang/rfcs/blob/master/README.md#what-the-process-is).

**Comment by synergixe** [comment]
> Next time make the rfc into PR using the [template](https://github.com/simple-lang/rfcs/blob/master/0000-template.md). Follow the instruction on the readme [here](https://github.com/simple-lang/rfcs/blob/master/README.md#what-the-process-is).

But the README says

>It's often helpful to get feedback on your concept before diving into the level of API design detail required for an RFC. You may open an issue on this repo to start a high-level discussion, with the goal of eventually formulating an RFC pull request with the specific implementation design.

Which is why this issue was created in the first place

**Comment by synergixe** [comment]
> ### basic way to define a function (with default argument value - primitive data types ONLY)
> Optional parameter is a load on the Virtual Machine and can affect speed and efficiency, the VM will have to call the functions with the optional parameter value if it not provide e.g
> 
> ```
> block printStr(text, suffix = "", pos = 0)
> 	if lengthOf(suffix) > 0 {
> 		text = text + suffix
>         }
> 
> 	stdout.println(text)
> ```
> If the function above **printStr** is invoked with only the text argument the VM will have to automatically call the function on behave on the developer with the the optional parameters in place
> 
> **in the source code**
> 
> ```
> printStr("Hello World")
> ```
> **translates to**
> 
> ```
> printStr("Hello World", "", 0)
> ```
> This implies the VM has to keep record of the optional parameters which will cost more resources as the optional parameter will remain in memory until the function is garbage collected (when there exist no reference to the function therein).
> 
> ### proposed way via overloading parameter names as argument labels
> This is just another layer of complexity to the language, using a label in the parameter will make the function less readable as function call itself will appear as if it the declaration.
> 
> ## Solution to the above
> The intents above can be achieved by using the list and variadic parameter. List is simple-lang is pure and can hold any other data types. List can also act as dictionary which make a lot of sense in this case.
> 
> The function can be declared with just one parameter which is list and the optional parameter can be
> sent as a list item or just ignored e.g
> 
> ```
> block printStr(params)
>         text = params["text"]
>         suffix = params["suffix"]
>         pos = params["pos"]
> 
> 	if lengthOf(suffix) > 0 {
> 		text = text + suffix
>         }
> 
> 	stdout.println(text)
> ```
> The above can be invoke with all the optional parameters (text, suffix, pos) intact or ignored. The following function call below is valid
> 
> ```
> printStr([ :text = "Hello World", :suffix = ".txt", :pos = 20 ])
> printStr([ :text = "Hello World", :suffix = ".txt" ])
> printStr([ :text = "Hello World" ])
> printStr([])
> ```
> The default value for no existing key index is null e.g. params["alien"] == null.
> Everything comes with a draw back, the drawback of using list is that the non existing key will be created which might cost some memory allocation but it is garbage collected at the end of execution of the function in contrast to the optional parameter which will have to exist even after the function has complete or even through out runtime.

Very apt!

Since there is a high chance of having slower runtime speeds, then i think your proposed solution is valid and is the best going forward. However, i believe it might be important to implement **destructuring** for arrays/lists (to be discussed in a separate issue).

I will create a standard pull request on this issue based on your solution so it can be discussed further

**Comment by synergixe** [comment]
or discussions can continue here...

**Comment by Thecarisma** [comment]
Close this and create another Issue for list destructing that is a bit interesting

**Comment by synergixe** [comment]
alright... closing out!
